"""Second migration

Revision ID: d56546048ee4
Revises: 
Create Date: 2021-11-16 18:34:11.779763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56546048ee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('user_firstname', sa.String(length=50), nullable=True),
    sa.Column('user_lastname', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('user_mobile', sa.String(length=12), nullable=True),
    sa.Column('user_dob', sa.String(length=20), nullable=True),
    sa.Column('user_gender', sa.String(length=2), nullable=True),
    sa.Column('user_profile_pic_url', sa.String(length=200000), nullable=True),
    sa.Column('user_create_dttm', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tbl')
    # ### end Alembic commands ###
